# Generated by Django 3.2.20 on 2024-01-10 13:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MemberSerializers',
            new_name='MemberSerializer',
        ),
    ]
