# Generated by Django 3.2.20 on 2024-01-10 13:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0002_rename_memberserializers_memberserializer'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MemberSerializer',
        ),
    ]
